### PR TITLE
Update favicon to new logo

### PR DESCRIPTION
**Pull request by bernardodsanderson**
As per issue #78, this PR updates the favicon to the new logo. It keeps the 32x32 size.

### CODE REVIEW

**Comment by pfrazee** [comment]
Appreciate the PR! Sorry we haven't merged it yet, we're in the middle of a big site update in a feature branch. I'm sure we'll pull this in after.

**Comment by mathiasrw** [comment]
Looks like the old favicon is still on the website. Is the site build and pushed manually to https://beakerbrowser.com/ ?

**Comment by taravancil** [comment]
@mathiasrw We just merged an hour ago - deploying later today

**Comment by pfrazee** [comment]
Done!

**Comment by mathiasrw** [comment]
BOOOOM - looks great :)

**Comment by pfrazee** [comment]
It does! Thanks for the help all

**Pull request merged**
